// Publications that back the explanatory claims on the site. Numbering follows this order everywhere
// (a <Cite id> shows [n] and links to /methodology#ref-<id>). Every entry was checked against the linked page.
export type Ref = {
  id: string; authors: string; year: string; title: string; venue: string; url: string; supports: string;
};

export const REFERENCES: Ref[] = [
  { id: "lebuhn2017", authors: "Lebuhn, H., Holm, A., Junker, S. & Neitzel, K.", year: "2017",
    title: "Wohnverhältnisse in Deutschland: eine Analyse der sozialen Lage in 77 Großstädten",
    venue: "Humboldt-Universität zu Berlin, funded by the Hans-Böckler-Stiftung (press release, 13 September 2017)",
    url: "https://www.boeckler.de/de/pressemitteilungen-2675-miete-vier-von-zehn-haushalten-in-deutschen-grossstaedten-tragen-eine-prekaer-hohe-3221.htm",
    supports: "Rent above 30% of household net income is treated as problematic, and many landlords use the same limit." },
  { id: "bundesbank2024", authors: "Deutsche Bundesbank", year: "2024",
    title: "Preise für Wohnimmobilien sanken 2023 deutlich; Mieten stärker unter Druck",
    venue: "Summary of the Bundesbank Monthly Report on the housing market",
    url: "https://www.bundesbank.de/de/aufgaben/themen/preise-fuer-wohnimmobilien-sanken-2023-deutlich-mieten-staerker-unter-druck-925398",
    supports: "Higher interest rates made buying unaffordable for many, and housing demand shifted towards the rental market." },
  { id: "greix-rent", authors: "Amaral, F., Jungwirth, P., Zdrzalek, J. & Zetzmann, S.", year: "2025",
    title: "Dokumentation für den Mietpreisindex (GREIX)",
    venue: "Kiel Institut für Weltwirtschaft, 12 June 2025",
    url: "https://www.kielinstitut.de/fileadmin/Dateiverwaltung/IfW_Unit/Macroeconomics/GREIX/Mietpreisindex/Greix_Mietpreisindex_Documentation.pdf",
    supports: "Asking rents in 37 cities from VALUE listing data, adjusted by hedonic regression for 21 characteristics including floor area, building age, rooms, condition, fittings and postcode." },
  { id: "bbsr-rents", authors: "Bundesinstitut für Bau-, Stadt- und Raumforschung (BBSR)", year: "2025",
    title: "Wohnungsmieten",
    venue: "BBSR Fachbeitrag, Wohnungs- und Immobilienmarktbeobachtung",
    url: "https://www.bbsr.bund.de/BBSR/DE/forschung/fachbeitraege/wohnen-immobilien/mieten-preise/mieten/wohnungsmieten.html",
    supports: "New-lease rents are well above existing rents because existing rents are adjusted to the market less often and rises for sitting tenants are capped by law." },
  { id: "iw2026", authors: "Sagner, P. & Voigtländer, M.", year: "2026",
    title: "In Großstädten: Mietangebote seit 2022 um bis zu 57 Prozent eingebrochen",
    venue: "Institut der deutschen Wirtschaft (IW), press release, July 2026",
    url: "https://www.iwkoeln.de/presse/pressemitteilungen/pekka-sagner-michael-voigtlaender-in-grossstaedten-mietangebote-seit-2022-um-bis-zu-57-prozent-eingebrochen.html",
    supports: "When new-lease rents are high, households stay longer, including in flats that no longer suit them." },
  { id: "gohl2019", authors: "Gohl, N.", year: "2019",
    title: "House prices and spatial mobility: Lock-in effects on the German rental market",
    venue: "Beiträge zur Jahrestagung des Vereins für Socialpolitik 2019, ZBW",
    url: "https://ideas.repec.org/p/zbw/vfsc19/203557.html",
    supports: "Academic study of the lock-in effect: the gap between sitting-tenant and new-lease rents reduces renters' mobility." },
  { id: "dmb2025", authors: "Deutscher Mieterbund", year: "2025",
    title: "Betriebskostenspiegel für Deutschland, Abrechnungsjahr 2024",
    venue: "Deutscher Mieterbund, 18 December 2025",
    url: "https://mieterbund.de/aktuelles/meldungen/mieterbund-veroeffentlicht-aktuellen-betriebskostenspiegel-fuer-deutschland/",
    supports: "Running costs averaged 2.67 € per m² and month in 2024, on top of the cold rent." },
  { id: "saxony2022", authors: "Sächsische Staatsregierung", year: "2022",
    title: "Sächsische Mietpreisbegrenzungsverordnung (SächsMPBVO), Begründung zu Indikator 5",
    venue: "REVOSax, 31 May 2022",
    url: "https://www.revosax.sachsen.de/vorschrift_gesamt/19656/44196.pdf",
    supports: "Citing the BBSR, the normal turnover vacancy a market needs is mostly given as 2 to 3% in the literature, sometimes 3 to 5%." },
  { id: "bgb556d", authors: "Bürgerliches Gesetzbuch", year: "2025",
    title: "§ 556d BGB, Abs. 2: Gebiete mit angespannten Wohnungsmärkten",
    venue: "German Civil Code",
    url: "https://dejure.org/gesetze/BGB/556d.html",
    supports: "German law names low vacancy with high demand, and population growth without enough new building, as signs of a tight housing market." },
  { id: "destatis2024", authors: "Statistisches Bundesamt (Destatis)", year: "2024",
    title: "Zensus 2022: 4,3 % aller Wohnungen stehen leer",
    venue: "Press release No. 46, 4 July 2024",
    url: "https://www.destatis.de/DE/Presse/Pressemitteilungen/Zensus2022-Pressemitteilungen/PM_zenus2022_46.html",
    supports: "Census vacancy figures for May 2022, including flats that could be occupied within three months." },
  { id: "eurostat2013", authors: "Eurostat, ILO, IMF, OECD, UNECE & World Bank", year: "2013",
    title: "Handbook on Residential Property Prices Indices (RPPIs)",
    venue: "Publications Office of the European Union",
    url: "https://ec.europa.eu/eurostat/web/products-manuals-and-guidelines/-/KS-RA-12-022",
    supports: "Standard reference for hedonic quality adjustment in housing price indices." },
  { id: "ke2017", authors: "Ke, G., Meng, Q., Finley, T., Wang, T., Chen, W., Ma, W., Ye, Q. & Liu, T.-Y.", year: "2017",
    title: "LightGBM: A Highly Efficient Gradient Boosting Decision Tree",
    venue: "Advances in Neural Information Processing Systems 30 (NeurIPS 2017)",
    url: "https://proceedings.neurips.cc/paper/2017/hash/6449f44a102fde848669bdd9eb6b76fa-Abstract.html",
    supports: "The gradient boosting library used for the forecasts." },
  { id: "koenker1978", authors: "Koenker, R. & Bassett, G.", year: "1978",
    title: "Regression Quantiles",
    venue: "Econometrica 46(1), 33–50",
    url: "https://doi.org/10.2307/1913643",
    supports: "Quantile regression: predicting a range (10th to 90th percentile) instead of a single value." },
  { id: "romano2019", authors: "Romano, Y., Patterson, E. & Candès, E. J.", year: "2019",
    title: "Conformalized Quantile Regression",
    venue: "Advances in Neural Information Processing Systems 32 (NeurIPS 2019)",
    url: "https://arxiv.org/abs/1905.03222",
    supports: "Calibrating quantile ranges so that they contain the stated share of real outcomes." },
  { id: "hyndman2021", authors: "Hyndman, R. J. & Athanasopoulos, G.", year: "2021",
    title: "Forecasting: Principles and Practice, 3rd edition, section 5.10 Time series cross-validation",
    venue: "OTexts, Melbourne",
    url: "https://otexts.com/fpp3/tscv.html",
    supports: "Rolling-origin back-testing: train only on data before each cut-off and score the forecast on what came after." },
  { id: "iglewicz1993", authors: "Iglewicz, B. & Hoaglin, D. C.", year: "1993",
    title: "How to Detect and Handle Outliers (as summarised in the NIST/SEMATECH e-Handbook of Statistical Methods, 1.3.5.17)",
    venue: "ASQC Quality Press",
    url: "https://www.itl.nist.gov/div898/handbook/eda/section3/eda35h.htm",
    supports: "Modified z-scores based on the median absolute deviation, with |z| above 3.5 flagged as a likely outlier." },
  { id: "unwup2018", authors: "United Nations, Department of Economic and Social Affairs, Population Division", year: "2018",
    title: "World Urbanization Prospects: The 2018 Revision. Key facts",
    venue: "United Nations, New York",
    url: "https://population.un.org/wup/assets/WUP2018-KeyFacts.pdf",
    supports: "Mumbai is among the world's largest cities, with close to 20 million inhabitants." },
  { id: "bhagat2016", authors: "Bhagat, R. B. & Jones, G. W.", year: "2016",
    title: "Demographic Dynamics of Mega-Urban Regions: The Case of Mumbai",
    venue: "Asia Research Institute Working Paper No. 201, National University of Singapore",
    url: "https://ari.nus.edu.sg/wp-content/uploads/2018/10/wps13_2014.pdf",
    supports: "Census 2011: Greater Mumbai had 12.47 million people, and 41.8% (5.2 million) lived in slums." },
  { id: "destatis-share", authors: "Statistisches Bundesamt (Destatis)", year: "2025",
    title: "Anteil der Wohnkosten am verfügbaren Haushaltseinkommen (EU-SILC)",
    venue: "Destatis table, Mikrozensus / EU-SILC",
    url: "https://www.destatis.de/DE/Themen/Gesellschaft-Umwelt/Wohnen/Tabellen/eurostat-anteil-wohnkosten-haushaltseinkommen-mz-silc.html",
    supports: "In 2025 housing took 24.1% of disposable income on average, but 43.7% for people at risk of poverty." },
  { id: "destatis-overburden", authors: "Statistisches Bundesamt (Destatis)", year: "2025",
    title: "Wohnkostenanteil und Wohnkostenüberbelastung (EU-SILC)",
    venue: "Destatis table, Mikrozensus / EU-SILC",
    url: "https://www.destatis.de/DE/Themen/Gesellschaft-Umwelt/Wohnen/Tabellen/eurostat-anteil-ueberbelastung-wohnkosten-mz-silc.html",
    supports: "In 2025, 11.2% of the population spent more than 40% of their income on housing; among people at risk of poverty it was 35.0%." },
  { id: "holm2021", authors: "Holm, A., Regnault, V., Sprengholz, M. & Stephan, M.", year: "2021",
    title: "Muster sozialer Ungleichheit der Wohnversorgung in deutschen Großstädten",
    venue: "Hans-Böckler-Stiftung, Working Paper Forschungsförderung No. 222",
    url: "https://www.boeckler.de/fpdf/HBS-008072/p_fofoe_WP_222_2021.pdf",
    supports: "Almost 13% of tenant households in Germany's 77 big cities have less than the subsistence minimum left after paying rent." },
];

export const REF_INDEX: Record<string, number> = Object.fromEntries(REFERENCES.map((r, i) => [r.id, i + 1]));
export const refById = (id: string) => REFERENCES[REF_INDEX[id] - 1];
